<?php
/**
 * AutoSound default Review product review template
 *
 * @author Yuri Chlek yurichhlek@gmail.com
 * @copyright 2020 Chlek
 */

/** @var \Magento\Review\Block\Product\Review $block */
?>

<div class="review-form-wrapper"
     data-bind="mageInit: {
        'Magento_Ui/js/modal/modal':{
            'type': 'popup',
            'trigger': '[data-trigger=trigger]',
            'responsive': true,
            'buttons': [{
                text: jQuery.mage.__('Close'),
                class: 'action'
            }]
        }}">
    <?= $block->getChildHtml(); ?>
</div>
<div id="product-review-container" data-role="product-review"></div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Review/js/process-reviews": {
                "productReviewUrl": "<?= $block->escapeJs($block->escapeUrl($block->getProductReviewUrl())); ?>",
                "reviewsTabSelector": "#tab-label-reviews"
            }
        }
    }
</script>
