<?php
/**
 * AutoStore default Catalog product list items template
 *
 * @author Yuri Chlek yurichhlek@gmail.com
 * @copyright 2020 Chlek
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Generic.WhiteSpace.ScopeIndent.Incorrect

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');

switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int)$block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int)$block->isShuffled();

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = count($block->getItems())) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
        break;

    default:
        $exist = null;
}
?>

<?php if ($exist) : ?>

<?php if ($type == 'related' || $type == 'upsell') : ?>
<?php if ($type == 'related') : ?>
<div class="block <?= $block->escapeHtmlAttr($class); ?>"
     data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}'
     data-limit="<?= $block->escapeHtmlAttr($limit); ?>" data-shuffle="<?= /* @noEscape */
$shuffle; ?>">
    <?php else : ?>
    <div class="block <?= $block->escapeHtmlAttr($class); ?>" data-mage-init='{"upsellProducts":{}}'
         data-limit="<?= $block->escapeHtmlAttr($limit); ?>" data-shuffle="<?= /* @noEscape */
    $shuffle ?>">
        <?php endif; ?>
        <?php else : ?>
        <div class="block <?= $block->escapeHtmlAttr($class); ?>">
            <?php endif; ?>
            <div class="block-title title">
                <?php if ($type === 'related'): ?>
                    <span class="before-title"><?= __("You may like this products"); ?></span>
                <?php endif; ?>
                <h2 class="products-title">
                    <strong class="title-strong" id="block-<?= $block->escapeHtmlAttr($class); ?>-heading"
                            role="heading"
                            aria-level="2"><?= $block->escapeHtml($title); ?></strong>
                </h2>
            </div>
            <div class="block-content content" aria-labelledby="block-<?= $block->escapeHtmlAttr($class); ?>-heading">
                <div class="products wrapper grid products-grid products-<?= $block->escapeHtmlAttr($type); ?>">
                    <ol class="products list items product-items owl-carousel">
                        <?php foreach ($items as $item) : ?>
                            <?php $available = ''; ?>
                            <?php if (!$item->isComposite() && $item->isSaleable() && $type == 'related') : ?>
                                <?php if (!$item->getRequiredOptions()) : ?>
                                    <?php $available = 'related-available'; ?>
                                <?php endif; ?>
                            <?php endif; ?>
                            <?php if ($type == 'related' || $type == 'upsell') : ?>
                                <li class="item product product-item" style="display: none;">
                            <?php else : ?>
                                <li class="item product product-item">
                            <?php endif; ?>
                            <div class="product-item-info <?= /* @noEscape */
                            $available ?>">
                                <?= /* @noEscape */
                                '<!-- ' . $image . '-->' ?>
                                <a href="<?= $block->escapeUrl($block->getProductUrl($item)); ?>"
                                   class="product photo product-item-photo">
                                    <?= $block->getImage($item, $image)->toHtml(); ?>
                                </a>
                                <div class="product details product-item-details">
                                    <div class="additional-information">
                                        <span class="sku-code"><?= __("Sku"); ?><span><?= __("&nbsp;:&nbsp;" . $item->getSku()) ?></span></span>
                                        <?php if ($qty = $StockState->getStockQty($item->getId()) > 10): ?>
                                            <span class='status in-stock'><?= __("In stock"); ?></span>
                                        <?php elseif ($qty = $StockState->getStockQty($item->getId()) <= 10 && $qty = $StockState->getStockQty($item->getId()) > 0):?>
                                            <span class='status ends'><?= __("Ends"); ?></span>
                                        <?php else:?>
                                            <span class='status ends'><?= __("Out of stock"); ?></span>
                                        <?php endif; ?>
                                    </div>
                                    <?php if ($showAddTo || $showCart) : ?>
                                        <div class="product actions product-item-actions">
                                            <?php if ($showAddTo) : ?>
                                                <div class="secondary-addto-links actions-secondary"
                                                     data-role="add-to-links">
                                                    <?php if ($addToBlock = $block->getChildBlock('product.wishlist.button.parent')) : ?>
                                                        <?= $addToBlock->setProduct($item)->getChildHtml(); ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                            <?php if ($showCart) : ?>
                                                <div class="actions-primary">
                                                    <?php if ($item->isSaleable()) : ?>
                                                        <?php if ($item->getTypeInstance()->hasRequiredOptions($item)) : ?>
                                                            <button class="action tocart primary"
                                                                    data-mage-init='{"redirectUrl": {"url": "<?= $block->escapeUrl($block->getAddToCartUrl($item)); ?>"}}'
                                                                    type="button"
                                                                    title="<?= $block->escapeHtmlAttr(__('Add to Cart')); ?>">
                                                                <span><?= $block->escapeHtml(__('Add to Cart')); ?></span>
                                                            </button>
                                                        <?php else : ?>
                                                            <?php $postDataHelper = $this->helper(Magento\Framework\Data\Helper\PostHelper::class);
                                                            $postData = $postDataHelper->getPostData($block->escapeUrl($block->getAddToCartUrl($item)), ['product' => $item->getEntityId()]); ?>
                                                            <button class="action tocart primary"
                                                                    data-post='<?= /* @noEscape */
                                                                    $postData ?>'
                                                                    type="button"
                                                                    title="<?= $block->escapeHtmlAttr(__('Add to Cart')); ?>">
                                                                <span><?= $block->escapeHtml(__('Add to Cart')); ?></span>
                                                            </button>
                                                        <?php endif; ?>
                                                    <?php else : ?>
                                                        <?php if ($item->getIsSalable()) : ?>
                                                            <div class="stock available">
                                                                <span><?= $block->escapeHtml(__('In stock')); ?></span>
                                                            </div>
                                                        <?php else : ?>
                                                            <div class="stock unavailable">
                                                                <span><?= $block->escapeHtml(__('Out of stock')); ?></span>
                                                            </div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                            <?php if ($showAddTo) : ?>
                                                <div class="secondary-addto-links actions-secondary"
                                                     data-role="add-to-links">
                                                    <?php if ($addToBlock = $block->getChildBlock('addto')) : ?>
                                                        <?= $addToBlock->setProduct($item)->getChildHtml(); ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                    <strong class="product name product-item-name"><a class="product-item-link"
                                                                                      title="<?= $block->escapeHtml($item->getName()); ?>"
                                                                                      href="<?= $block->escapeUrl($block->getProductUrl($item)); ?>">
                                            <?= $block->escapeHtml($item->getName()); ?></a>
                                    </strong>
                                    <?= $block->getReviewsSummaryHtml($item, $templateType); ?>
                                    <?= /* @noEscape */
                                    $block->getProductPrice($item); ?>
                                    <?php if ($templateType) : ?>
                                        <?= $block->getReviewsSummaryHtml($item, $templateType); ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            </li>
                        <?php endforeach ?>
                    </ol>
                </div>
            </div>
        </div>
        <?php endif; ?>
<script type="text/x-magento-init">
    {
        ".owl-carousel":{
            "owlInclude":{}
        }
    }
</script>
