<?php
/**
 * AutoSound Theme socialmedia template
 *
 * @author Yuri Chlek yurichhlek@gmail.com
 * @copyright 2020 Chlek
 */

/** @var $block \Magento\Catalog\Block\Product\View */

?>
<?php $_product = $block->getProduct(); ?>
<div class="product-addto-links" data-role="add-to-links">
    <?= $block->getChildHtml("product.info.socialmedia") ?>
    <?php if ($_product->isSaleable()) : ?>
        <?= $block->getChildHtml("view.addto.wishlist") ?>
    <?php endif; ?>
    <?= $block->getChildHtml("view.addto.compare") ?>
</div>
